### PR TITLE
Extend inlay hint support for type hints

### PR DESCRIPTION
**Pull request by HighCommander4**
Corresponding server-side patch: https://reviews.llvm.org/D102148

### CODE REVIEW

**Comment by HighCommander4** [comment]
Requesting review, the server-side patch has merged but we need this client-side bit for users to actually see the type hints.

**Comment by HighCommander4** [comment]
Review ping :)

**Comment by HighCommander4** [comment]
@sam-mccall pinging again :) This is a small patch to enable type hints on the client side, so that the server-side type hints patches that we've been merging can actually be used. Would be great to merge!

**Review by sam-mccall — APPROVED** [review]
Thanks for the pings, sorry about delaying this

**Pull request merged**
