### PR TITLE
Release version 0.1.25

### PR DESCRIPTION
**Pull request by HighCommander4**

### CODE REVIEW

**Comment by HighCommander4** [comment]
(Marking as WIP since we should probably include #515 in the release)

**Comment by xidianzhangjun** [comment]
When will v0.1.25 be released?

**Comment by HighCommander4** [comment]
> When will v0.1.25 be released?

I finally got to reviewing #515, apologies for the delay. Once #515 merges, I will resubmit this for review.

**Comment by HighCommander4** [comment]
> Once #515 merges, I will resubmit this for review.

#515 has now merged, and I've resubmitted this for review.

**Comment by xidianzhangjun** [comment]
What's new in this version and when will it be released? 💯 : )

**Comment by HighCommander4** [comment]
> What's new in this version

You can see what's new since the last release in the [changelog entry](https://github.com/clangd/vscode-clangd/pull/516/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed) which this PR completes.

I'd say the most notable change is #193.

> and when will it be released? 💯 : )

It will be released when this PR is merged and the command to publish the new release to the VSCode extension marketplace is run.

@sam-mccall @hokein ^ I would appreciate a review on this

**Comment by simon8233** [comment]
Sorry , may I know where I can download latest 0.1.25 to testing?

**Comment by HighCommander4** [comment]
> Sorry , may I know where I can download latest 0.1.25 to testing?

We don't currently have anything in the way of snapshot releases (https://github.com/clangd/vscode-clangd/issues/517 is on file about that), so the current way would be to build the extension from source.

Instructions for that can be found at https://github.com/clangd/vscode-clangd/issues/517. The extension can be packaged into a `.vsix` file using `npm run package`.

**Comment by xidianzhangjun** [comment]
> > Sorry , may I know where I can download latest 0.1.25 to testing?
> 
> We don't currently have anything in the way of snapshot releases (#517 is on file about that), so the current way would be to build the extension from source.
> 
> Instructions for that can be found at https://github.com/clangd/vscode-clangd/blob/master/DEVELOPING.md. The extension can be packaged into a `.vsix` file using `npm run package`.

The review seems to be pended. :-;

**Comment by HighCommander4** [comment]
@kadircet perhaps you could help out with getting this new release out? I think users are eager to try out the new inactive regions presentation implemented in #193 (and I'm eager to hear feedback about it and start thinking about next steps such as proposing the protocol for addition to LSP).

**Comment by HighCommander4** [comment]
I'm going to go ahead and merge this patch without review; I hope that's fine, since the contents of the patch itself are just an update to the changelog and version metadata and so shouldn't be controversial in any way.

However, I don't have the permission to publish the new version to the VSCode Marketplace -- @sam-mccall @kadircet @hokein could one of you please do that?

**Comment by HighCommander4** [comment]
> However, I don't have the permission to publish the new version to the VSCode Marketplace -- @sam-mccall @kadircet @hokein could one of you please do that?

It appears I was mistaken about there being a manual publication step, since 0.1.25 automatically appeared on the [marketplace](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd).

(I do now see that there is a Github Action that [runs](https://github.com/clangd/vscode-clangd/blob/master/.github/workflows/auto-release.yml#L39) `npm run publish` when `package.json` changes.)

**Pull request merged**
