### PR TITLE
Release version 0.1.29

### PR DESCRIPTION
**Pull request by HighCommander4**

### CODE REVIEW

**Review by hokein — APPROVED** [review]
Thanks for taking care of all the reviews.

**Comment by HighCommander4** [comment]
@hokein It looks like the "Publish release" workflow [failed](https://github.com/clangd/vscode-clangd/actions/runs/9903567317/job/27359310583#step:9:34) with "You're using an expired Personal Access Token, please get a new PAT" -- is that something you can refresh?

**Comment by hokein** [comment]
I have re-generated the token (the maximum validity of an access token is 1 year) and re-ran the release workflow. The new release has been rolled out.

**Comment by HighCommander4** [comment]
> I have re-generated the token (the maximum validity of an access token is 1 year) and re-ran the release workflow. The new release has been rolled out.

Thanks very much!

**Pull request merged**
