### PR TITLE
Prompt when workspace overrides clangd.path and clangd.arguments

### PR DESCRIPTION
**Pull request by sam-mccall**

### CODE REVIEW

**Review by hokein — APPROVED** [review]
Thanks, looks pretty solid. I also test it locally.

**Comment by adzenith** [comment]
Is there any way to reset this if you accidentally click "no" at the prompt?

**Comment by sam-mccall** [comment]
We save the answer for the latest value seen of each setting. So you can change the setting in workspace/.vscode/settings.json and reload the window to get re-prompted. (And then, change it back!)

**Comment by simon8233** [comment]
is it any way to disable it? 
like $HOME/.clangd_config
we use clangd.path and clangd.arguments and remote index server setup as one workspace file in internal.

**Comment by HighCommander4** [comment]
@simon8233 it might be easier for the question to be noticed if you file a new issue for it

**Comment by simon8233** [comment]
Thanks for your feedback. I will raise question for this.

**Pull request merged**
