### PR TITLE
show better error message when no function found during prepareCallHierarchy

### PR DESCRIPTION
**Pull request by sheldonneuberger-sc**
Slight improvement on https://github.com/clangd/vscode-clangd/issues/247, here we now show a "No function found at cursor location." information message if the user selects "Show Call Hierarchy" on a non-function.

### CODE REVIEW

**Comment by kadircet** [comment]
We try to keep the vscode-clangd as thin as possible. I am not sure if the extra error message carries enough weight to justify the costs. Why do you think the new UX in vscode with `No results found` is not enough?

**Comment by sheldonneuberger-sc** [comment]
Here's my line of thinking: most users of this extension who see "No results found" will think "clangd doesn't know of any callers for this function". But that's actually not true, what really happened is "clangd doesn't believe this is a function".

So when someone does "Show Call Hierarchy" on something that isn't supported yet by clangd, this gives a clearer picture of what's going on to the user.

I see what you're saying about keeping this extension as thin as possible, although the additional weight here is small. Let's see what @jrieken comes up with on the vscode bug https://github.com/microsoft/vscode/issues/137415, maybe that will avoid this problem entirely.

Thanks for the guidance on this @kadircet.

**Comment by jrieken** [comment]
This is an issue in VS Code and your call hierarchy provider should not be showing/driving the UI. Always consider that other extensions, like LiveShare, can "drive" your provider in different scenarios and that UI messages look very out of place than

**Comment by kadircet** [comment]
> Here's my line of thinking: most users of this extension who see "No results found" will think "clangd doesn't know of any callers for this function". But that's actually not true, what really happened is "clangd doesn't believe this is a function".
>
> So when someone does "Show Call Hierarchy" on something that isn't supported yet by clangd, this gives a clearer picture of what's going on to the user.

I don't feel like there's a big difference between the two. You're right that `No results` is not enough to disambiguate between whether the language server failed to find a `callable` at cursor or failed to find any `callers/callees` for the `callable`. But this won't prevent a user from going and filing a bug if they think there should've been an answer to their request and later on it's on the language server maintainer to try and figure out what went wrong anyways.

> I see what you're saying about keeping this extension as thin as possible, although the additional weight here is small.

I don't agree with this one. Yes it's small in number of lines, but it is actually a whole new concept about intercepting all the calls between VSCode and the languageserver, which is a great power. Hence will require more responsibility in the future to make sure we're not introducing too much new hooks to make the interaction between the client and server surprising. This is a lot of mental effort for maintenance and as @jrieken pointed out it'll also be surprising for users that work with multiple language servers or different plugins.

**Comment by sheldonneuberger-sc** [comment]
Thanks @kadircet and @jrieken for taking the time to explain, it makes sense to me now. Will close this one.

**Pull request closed without merging**
